FROM node:22-alpine

WORKDIR /app

# pnpm 설치
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

# 빌드 (필요하면)
RUN pnpm run build

# 빌드 결과물을 실행
CMD ["node", "dist/main"]