# 1. 빌드 단계
FROM node:22-alpine AS builder

WORKDIR /app

RUN corepack enable pnpm

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build

# 2. 실행 단계 (최소한의 의존성만)
FROM node:22-alpine

WORKDIR /app

RUN corepack enable pnpm
RUN apk add --no-cache ffmpeg

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/public ./public

EXPOSE 3000

CMD ["node", "dist/main.js"]