services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  app:
    image: streaming-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
      - ./uploads/media:/app/uploads/media
    depends_on:
      - db
    restart: always

volumes:
  db_data: